[mod]
id = "eg_more_multiplayer_players"
name = "Enchanted's Template Mod"
description = "Multi-version, multi-loader mod template for Minecraft using Stonecutter."
group = "games.enchanted"
version = "0.1.0"
license = "PolyForm Shield License 1.0.0"
source_url = "https://github.com/Enchanted-Games/more-multiplayer-players"
issue_tracker = "https://github.com/Enchanted-Games/more-multiplayer-players/issues"
icon = "assets/eg_more_multiplayer_players/icon.png"

# neoforge versions: https://projects.neoforged.net/neoforged/neoforge
# fabric versions: https://fabricmc.net/develop/

[fabric]
deps.fabric-loader = "0.18.5"
dep_str.fabric-loader = ">=0.18"

["26.2"]
deps.minecraft = "26.2-snapshot-7"

[fabric."26.2"]
dep_str.minecraft = ">26.1 <26.3"

deps.fabric-api = "0.148.3+26.2"
dep_str.fabric-api = ">=0.148.3+26.2"

#deps.modmenu = "18.0.0-alpha.8"

[neoforge."26.2"]
dep_str.minecraft = "[26.1,26.2)"

deps.neoforge = "26.1.2.21-beta"